### ISSUE TITLE
Question about the status of this integration

### ISSUE THREAD

**Issue by achambers** [getsentry/sentry-fullstory#21]
Hi.

Firstly, nice work on this. Thanks.

I've been following this integration for a little while now and was just wondering what the status of it is? Would you say it's ready for production consumption?

When I looked last it wasn't published to npm so I implemented it myself. I see now that it is published. Are we good to start using this in production apps?

**Comment by patrick-fs** [comment]
Hi @achambers thanks for keeping an eye on this project! Yes, it is ready for prime-time. Please feel free to use it in your production apps.

If there's anything you feel needs improvement, please let us know.
