### ISSUE TITLE
The documentation needs correction

### ISSUE THREAD

**Issue by deepikagunda** [getsentry/sentry-fullstory#22]
import SentryFullStory from '@sentry/sentry-fullstory'; needs to be changed to import SentryFullStory from '@sentry/fullstory';

FullStory.init({ orgId = '__FULLSTORY_ORG_ID__' }); needs to be changed to 
FullStory.init({ orgId : '__FULLSTORY_ORG_ID__' });

**Comment by scefali** [comment]
@deepikagunda Good catch! Fixing...
