### ISSUE TITLE
The sentry URL shown in fullstory is pointing to non-existant sentry event .

### ISSUE THREAD

**Issue by deepikagunda** [getsentry/sentry-fullstory#25]
Thanks for this integration plugin . I am facing an issue though . On some of the events , the fullstory is showing a sentry URL which we use in the browser shows that the event is not existing one. 

I searched the error up based on IP and was able to see a sentry entry but the event id is different from the one which was found in the sentry URL in the fullstory website.

Can you help.

**Comment by scefali** [comment]
@deepikagunda Hi there, thanks for writing in again. Could you provide more details on the URL and the event that didn't work as expected? If you don't want to share publicly here, you can email me at scefali@sentry.io.

**Comment by deepikagunda** [comment]
Thanks for responding . Sent you an email Stephan.

**Comment by scefali** [comment]
@deepikagunda Thanks for emailing me with the details. I believe what happened with the error that could not be found is that it never reached the Sentry servers. The Sentry event ID is created on the client device before it is sent to Sentry so there's always the possibility that the request gets dropped. This is problematic for events on mobile devices where connectivity is often disrupted. Unfortunately, the client is unaware of the Sentry issue ID so we can't link directly to the issue independent of the individual event. Such is the limitation of this integration in its current state.
