### ISSUE TITLE
Cannot read property 'message' of null

### ISSUE THREAD

**Issue by kalley** [getsentry/sentry-fullstory#34]
I'm getting quite a few of these in my Sentry logs. Which means the error I want to get is getting swallowed up. It's happening due to another library that creates an Error Event and then dispatches that; without an error property. So that property is `null`, which is valid.

In `getOriginalExceptionProperties`, `originalException` is assumed to be on `EventHint`. The type for that in `@sentry/types` is `Error | string | null`. Further, `hint` is assumed to be present, but according the `EventProcessor` type, it could be `undefined`. More than happy to push a PR for these changes. Didn't know if there were any specific guidelines you need me to follow.

**Comment by scefali** [comment]
@kalley If you're willing to make a PR, go for it! If there are any issues with it, I'll be sure to leave it a comment. Please add me on the PR as well.
