### ISSUE TITLE
FullStory integration says "Enabled" but no links appear in error reports

### ISSUE THREAD

**Issue by tennisgent** [getsentry/sentry-fullstory#44]
This was working at one time, but the links stopped appearing on our error reports some time ago and we'd like to get them back. 

![CleanShot 2020-08-11 at 21 32 25](https://user-images.githubusercontent.com/1782077/89972087-2b2f4500-dc1a-11ea-8e78-3b3009574d5a.png)

The id for our organization is `successfund`

Any tips you can suggest would be greatly appreciated

**Comment by scefali** [comment]
@tennisgent Sorry for the late reply. Based on what I'm seeing, you're using the Node SDK and this integration only works with the front end Javascript SDK.

**Comment by tennisgent** [comment]
@scefali We're using both the frontend browser sdk as well as the node sdk. We don't get fullstory links in either case, no matter where the issue is logged. 

Here's an example of an issue that was logged using the browser sdk: https://sentry.io/organizations/successfund/issues/1898063481/?project=1386885

**Comment by tennisgent** [comment]
@scefali Any updates here?

**Comment by scefali** [comment]
@tennisgent It's difficult for me to debug this without seeing your code in how you are initializing Sentry and capturing exceptions. Do you see any console errors happening that might be related to the integration?
