### ISSUE TITLE
FS.getCurrentSessionURL not ready

### ISSUE THREAD

**Issue by willashe** [getsentry/sentry-fullstory#46]
I'm trying to integrate our Sentry and Fullstory accounts using this package, but after following the setup instructions it appears that any Sentry exceptions that are captured on initial page load happen before Fullstory is fully bootstrapped.  When I throw after the app has loaded, things appear to work correctly.

For more context: this is a React app, using Sentry and Fullstory JavaScript SDKs (via NPM), and manually calling `Sentry.captureException` from inside a component.  When I load the app homepage and navigate to the route that mounts this component, I see correct links between Sentry/Fullstory.  But when this component is mounted on initial page load (visit URL directly), I see the following:

- `FS.getCurrentSessionURL not ready` shown in JS console
- Sentry error page shows `current session URL API not ready` under fullStoryUrl

How can I make sure Fullstory is fully bootstrapped so I can capture errors that may happen on page load?

**Comment by patrick-fs** [comment]
Hey @willashe thanks for raising this issue and apologies for the delayed reply. You've got it right, there are errors being thrown before FullStory is fully bootstrapped, and our `getCurrentSessionURL` function isn't defined until bootstrapping is complete - thus the "not ready" messages that are showing up in Sentry. There is a server call that needs to happen before `getCurrentSessionURL` is ready (see [this article ](https://help.fullstory.com/hc/en-us/articles/360032975773-How-does-FullStory-recording-work-to-recreate-my-users-experience-) for more details). However, calls to `FS.event` can be made prior to bootstrapping and will be recorded once FullStory is ready. We record the Sentry URL for all errors captured by Sentry, so you can search for them and find them in FullStory. Does this help you?

**Comment by willashe** [comment]
Hey @patrick-fs yes sir, very helpful, thank you!
