### ISSUE TITLE
Links in Sentry not accessible to Guest fullstory users

### ISSUE THREAD

**Issue by mkj28** [getsentry/sentry-fullstory#47]
As a developer reviewing Sentry issue I would like to be able to click into fullstory URL in Sentry to take me to the session. I would like to take advantage of "guest" functionality in Fullstory - since the use case is viewing very specific sessions.

Currently using sentry-fullstory integration requires creating full Fullstory user accounts, unnecessarily consuming Sentry seats (which Fullstory makes you pay for for some reason... on top of sessions...).

**Comment by patrick-fs** [comment]
Hi @mkj28 thank for reaching out. Yes, FullStory pricing is based on session quota and seat count. It is possible to share specific sessions with people who don't have seats using our [Guest Seat](https://help.fullstory.com/hc/en-us/articles/360020624294-Sharing-Sessions-with-Guests) feature, but these session links can only be created by folks who have a seat on FullStory. You do need a FullStory seat to view the session links generated by the FullStory API.

Does this workflow help you: someone with a FullStory seat links to a session replay from Sentry, then creates a Guest Seat to share the link with others on your team who don't have a paid seat?

**Comment by mkj28** [comment]
> Does this workflow help you: someone with a FullStory seat watches a session replay link from Sentry, then creates a Guest Seat to share the link with others on your team who don't have a paid seat?

not really for the sentry<>fullstory integration - in this case the developer reviewing sentry would be also the one accessing fullstory. Ideally these links (the ones added to fullstory) are guest-accessible.
