### ISSUE TITLE
Error: FullStory is not loaded, please ensure the init function is invoked before calling FullStory API

### ISSUE THREAD

**Issue by sohinim98** [getsentry/sentry-fullstory#48]
Sentry keeps throwing the `FullStory is not loaded, please ensure the init function is invoked before calling FullStory API` error.
This is an Angular2 app and I'm initializing FullStory from `app.component.ts` like this -
```
// fullStory analytics tracking
        FullStory.init({ orgId: environment.fullstoryOrgId,
          devMode: !environment.production });
        FullStory.identify(this.user._id, {
          displayName: this.user.name,
          email: this.user.email,
          institution: this.user.org_name,
        });
```

We have integrated Sentry with Fullstory using [@sentry/fullstory](https://www.npmjs.com/package/@sentry/fullstory) and we initialize sentry in a separate `entry-error-handler.ts` file and capture using `Sentry.captureException(error.originalError || error);`.

I tried checking if `FullStory.getCurrentSessionURL();` was ready before my `FullStory.identify` call and it wasn't meaning that FullStory wasn't fully bootstrapped. I also read that calls to FS.event can be made prior to bootstrapping and the only time we really need FullStory to be fully bootstrapped is for session replay url (or session replay id) which we're not using.

Since there isn't an `FullStory.OnReady()` function for FullStory, what's the suggested solution?

**Comment by scefali** [comment]
@sohinim98 Is this related to this other issue: https://github.com/getsentry/sentry-fullstory/issues/46

**Comment by robinjhuang** [comment]
Hi, I'm also encountering this error. Are you suggesting we can only look up the error in Fullstory?

**Comment by SonnyFishback** [comment]
I've also had this experienced this issue in my Vue wep app. It seems like the only way to fix this is to ensure that FullStory is initialized before Sentry and also give FullStory enough time to make the Session URL available by using a timeout. After playing with the timeout length, it seems the FullStory API needs about 620 milliseconds before the session url is available.

The downside to this is that all errors that occur in your application in the first second aren't captured.

This is what I'm doing. I hope it helps someone!

In ./main.js

```javascript

try {
  FullStory.init({
    orgId: `${process.env.VUE_APP_FULLSTORY_ORG_ID}`,
    debug: true
  })
} catch (e) {
  Sentry.captureException(e)
}


window.setTimeout(() => {
  try {
    const enabled = process.env.VUE_APP_SENTRY_ENABLED || 'true'
    const debug = process.env.VUE_APP_SENTRY_DEBUG || 'true'
    const logErrors = process.env.VUE_APP_SENTRY_LOG_ERRORS || 'true'
    const env = process.env.VUE_APP_SENTRY_ENVIRONMENT || 'development'
    Sentry.init({
      app,
      enabled: enabled === 'true',
      environment: env,
      dsn: process.env.VUE_APP_SENTRY_DSN,
      integrations: sentryIntegrations,
      debug: debug === 'true',
      logErrors: logErrors === 'true',
      tracesSampleRate: parseFloat(process.env.VUE_APP_SENTRY_TRACES_SAMPLE_RATE) || 1.0,
      normalizeDepth: -1,
      beforeSend (event, hint) {
        try {
          // console.log(`SENTRY EVENT:\n${JSON.stringify(event, null, 2)}`)
        } catch (error) {
          // swallow
        }
        return event
      }
    })
  } catch (e) {
    // swallow
  }
}, 620)
```
