### ISSUE TITLE
Will not work for on premises instalations

### ISSUE THREAD

**Issue by dagadbm** [getsentry/sentry-fullstory#49]
My sentry on premise instalation does not have a /organizations route its just https://sentry.mycompany.com/sentry.
/organizations does  not exist.
I have looked at the source  code and even  though you can change the base URL of sentry it still forces the  /organizations.

**Comment by scefali** [comment]
@dagadbm Hey, thanks for writing in. What version of Sentry are you using?

**Comment by dagadbm** [comment]
I have no idea. How can I check that?

Thanks for replying!

**Comment by dagadbm** [comment]
Found it!
Sentry 9.1.2

**Comment by scefali** [comment]
@dagadbm yea, you're just using an outdated version of Sentry. This package only works with Sentry 10+. I'll update the docs to reflect that.

**Comment by dagadbm** [comment]
Is there a way to support older versions ? Or is it easy for me to do this
manually ? To integrate an older version of sentry with full story?

**Comment by scefali** [comment]
@dagadbm If you want to support an older version, you'll have to fork this repo and make the changes that you want.
