### ISSUE TITLE
Does fullstory integration works with @sentry/electron

### ISSUE THREAD

**Issue by vgrbr** [getsentry/sentry-fullstory#51]
### Question
Does Fullstory plugin work with @sentry/electron SDK?

I tried to implement it same way as for @sentry/browser but it does not work - is there any way to have this integration with @sentry/electon

**Comment by scefali** [comment]
This package does not work with it but there is probably a way to do it that's similar

**Comment by vgrbr** [comment]
Thank you for quick answer.
