### ISSUE TITLE
Sentry links in FS for sentry traces are incorrect

### ISSUE THREAD

**Issue by jasondeng** [getsentry/sentry-fullstory#57]
When using this library with https://www.npmjs.com/package/@sentry/tracing, traces are captured and reported in FS as errors. 

The supplied link in the Fullstory event is incorrect and leads to search page with no results. It would nice to not report it as an error and to be able to fix the link or have this as an opt-in option.

Incorrect link for trace - `https://sentry.io/organizations/<org_slug>/issues/?project=<product_id>&query=<event_id>`
Link should be something like this instead (only if we want to report on trace event)- `https://sentry.io/organizations/<org_slug>/performance/<environment>-<event_id>/?project=<project_id>`

**Comment by leeandher** [comment]
Thanks for letting us know! As per 1.1.6 Fullstory won't pick up tracing events from Sentry, so no need to correct the link. Only errors will be recorded which still have the correct link.
