### ISSUE TITLE
React Native Sentry-FullStory Integration

### ISSUE THREAD

**Issue by andaydev** [getsentry/sentry-fullstory#72]
As, currently, Sentry-FullStory integration is [yet to be implemented in React Native](https://github.com/getsentry/sentry-react-native/issues/1966), may I ask: Is there an easy way for us to manually search for the session in Fullstory? For example, does Sentry/Fullstory capture a session id that can be referenced in both?

**Comment by jayfeldman12** [comment]
@andaydev  The release of 2.0.0 is meant to make this library work in React Native by allowing the client to be passed in to the plugin initialization, but personally I wasn't able to make it work--raised an issue for it [here](https://github.com/getsentry/sentry-fullstory/issues/82). Could be worth trying it yourself if you're still working on the project though!
