### ISSUE TITLE
A portion of the FullStory URL is filtered out

### ISSUE THREAD

**Issue by Aaronius** [getsentry/sentry-fullstory#73]
### Environment

How do you use Sentry?
SaaS

Which SDK and version?
@sentry/fullstory@1.1.8
@sentry/react@6.17.3

### Steps to Reproduce

Throw an error.

### Expected Result

A valid FullStory URL displayed for the error in the Sentry UI.

### Actual Result

An invalid URL because Sentry filtered out a portion:

```
https://app.fullstory.com/ui/NF3HD/session/[Filtered]%3A4569975532609536%3A1645115525556
```

I'm not sure what to do about this to not have filtering on the URL. Thanks!

**Comment by A-Farag** [comment]
I am also experiencing the same issue. Any update on this?

**Comment by somogyibence** [comment]
@Aaronius @A-Farag we just had the same issue! You can solve it by adding the `fullStoryUrl` field to the `Global Safe Fields` under Settings > [Your project] > Security & Privacy > DATA SCRUBBING and voila your full story URLs will be restored :)

**Comment by Aaronius** [comment]
Nice find @somogyibence! Thanks!
