### ISSUE TITLE
Support integration with @sentry/nextjs

### ISSUE THREAD

**Issue by mcmxcdev** [getsentry/sentry-fullstory#80]
It seems that the current integration only works with `@sentry/browser`.

With Next.js, the `FullStory.init()` invocation is triggered inside a `useEffect` hook in `_app.tsx`, so it's pretty different from the instructions in the README and would need to be accounted for.

**Comment by seanparmelee** [comment]
You could call `FullStory.init()` in the `sentry.client.config.ts` file, passing in a callback that adds the integration to Sentry:

```typescript
import * as FullStory from '@fullstory/browser';
import SentryFullStory from '@sentry/fullstory';
import * as Sentry from '@sentry/nextjs';

Sentry.init({
  dsn: __DSN__,
  // ...
});

FullStory.init({ orgId: '__FULLSTORY_ORG_ID__' }, () => {
  Sentry.getClient()?.addIntegration?.(
    new SentryFullStory('__SENTRY_ORG_SLUG__', { client: FullStory }),
  );
});
```
