### ISSUE TITLE
Add tag for "hasFullstory" or similar to sentry for searchability

### ISSUE THREAD

**Issue by dan-kez** [getsentry/sentry-fullstory#81]
Hi all,

We leverage sentry and fullstory together but heavily sample fullstory events for a variety of reasons. Due to this, we do not have a fullstory url in the context for _every_ sentry event. Usually though at least one event in an issue will have the fullstory url in context.

The challenge here is that sentry's UI does not allow to search for the present of a context variable, only tags.

It would be ideal to include, whether by default or opt in, a `hasFullstory` or similar tag to enable users to find sentry events with fullstory urls to expedite triage.

**Comment by AbhiPrasad** [comment]
SDKs typically do not add tags for users, we recommend adding this yourself via some custom code.
