### ISSUE TITLE
Support Sentry v8

### ISSUE THREAD

**Issue by okize** [getsentry/sentry-fullstory#91]
it looks like class-based integrations have been removed in Sentry v8: https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#removal-of-class-based-integrations

### Environment

`@sentry/fullstory@npm:2.1.0 [582bf] (via npm:^2.1.0 [582bf])` in `Node v20.9.0`

### Steps to Reproduce

1. upgrade `@sentry/core` to v8 
2. upgrade `@sentry/react` to v8

### Expected Result

I expected no Typescript errors

### Actual Result

Typescript error:
```sh
webpack/datadogRum/initializeSentryClient.ts:50:7 - error TS2322: Type 'SentryFullStory' is not assignable to type 'Integration'.
  Types of property 'setupOnce' are incompatible.
    Type '(addGlobalEventProcessor: (callback: EventProcessor) => void, getCurrentHub: () => Hub) => void' is not assignable to type '() => void'.
      Target signature provides too few arguments. Expected 2 or more, but got 0.

50       new SentryFullStory('wistia', { client: FullStory }),
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in webpack/datadogRum/initializeSentryClient.ts:50
```

code:
```ts
  Sentry.init({
    integrations: [
      Sentry.browserTracingIntegration(),
      new SentryFullStory('wistia', { client: FullStory }),
    ],
    ...
  });
```

**Comment by AbhiPrasad** [comment]
Released! https://www.npmjs.com/package/@sentry/fullstory/v/3.0.0

**Comment by okize** [comment]
@AbhiPrasad confirmed installing v3 & updating integration config fixed the typescript error, thank you!! 🙏

**Comment by RMHonor** [comment]
For anyone that comes here with this TypeScript issue despite upgrading both `@sentry/browser` and `@sentry/fullstory` to latest, check that you've not got an old version of `@sentry/types` installed. You can see this by running `npm list @sentry/types`.

For us, we had an old version of `@sentry/vite-plugin` which was pulling in an old version.
